name: 循环执行脚本

on:
  schedule:
    - cron: '*/30 * * * *'  # 每隔6小时执行一次

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 执行脚本
        run: python3 main2.py
